#Mandatory should port forward py container
#kubectl port-forward py-service-6bdf59f868-xc9ml 8001
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: py-server 
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: py-server
  template: 
    metadata: 
      labels: 
        app: py-server
    spec: 
      containers: 
        - name: py-server
          image: localhost:32000/py-server
          ports:
            - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: py-service
spec:
  selector:
    app: py-server
  ports:
    - protocol: TCP
      port: 8001      # Port exposed by the Service
      targetPort: 8001  # Port on the container
