# Always see the service description before init
apiVersion: v1
kind: Service
metadata:
  name: py-serr
spec:
  type: NodePort
  selector:
    app: py-serv
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30015
