apiVersion: apps/v1
kind: Deployment
metadata:
  name: externalscaler
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: externalscaler
  template:
    metadata:
      labels:
        app: externalscaler
    spec:
      containers:
      - name: externalscaler
        image: externalscaler:latest
        imagePullPolicy: Never
        resources:
          requests:
            cpu: "20m"
            memory: "64Mi"
          limits:
            memory: "150Mi"
        ports:
        - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: externalscaler
  namespace: default
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app: externalscaler
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: php-apache-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: php-apache
  pollingInterval: 10
  # cooldownPeriod:  20
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: external
      metadata:
        scalerAddress: externalscaler:50051
